apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-old-sessions
spec:
  schedule: "0 * * * *"
  startingDeadlineSeconds: 200
  ttlSecondsAfterFinished: 100
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: clear-sessions
              image: artemzinukov/django-app:v3
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: app-secret
          restartPolicy: OnFailure